{% set name = "napari-yapic-prediction" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-yapic-prediction-{{ version }}.tar.gz
  sha256: 02ef748c83984ffde15d006a9847f528686b5fd50cdb3e7761e7a9fb892004ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.6
    - scikit-image
    - yapic

test:
  imports:
    - napari_yapic_prediction
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yapic/napari-yapic-prediction
  summary: napari widget that performs image segmentation with yapic model.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - pranjaldhole
